#ACISS
MATLAB_DIR=/usr/local/packages/MATLAB/R2011b
CUDA_DIR = /usr/local/packages/cuda/4.0

#Generic
#MATLAB_DIR=/opt/Matlab/R2012a
#CUDA_DIR = /usr/local/cuda

# Depending on version of Teslas installed
CUDA_LDIR = lib64
CUDA_ARCH = sm_20



