#!/bin/bash

# --- Test for results directory --- #
resDir="${HOME}/Results"
if [ -d $resDir ]; then
  activeResDir=$resDir
else
  mkdir "${HOME}/Results/"
  echo ">>> WARNING: No Results directory found. One has been created."
fi

if [ -z "${1}" ]; then
  echo ">>> ERROR: No input specified. How to run (./imogen help):"
  ./imogen help
  exit 1
fi

if [ ${1} = "help" ]; then
  echo "       /=============\\"
  echo "+----=< *IMOGEN HELP* >=======----------------------------------------"
  echo "|      \\=============/"
  echo "|"
  echo "| Serial operation: ./imogen serial   runfile streamnumber GPUn"
  echo "| Local parallel:   ./imogen parallel runfile streamnumber GPUs #procs"
  echo "| Cluster submit:   ./imogen cluster  runfile streamnumber [GPUs [nodes [ppn [queue [np]]]]]"
  echo "|                   (tees realtime output to ~/imogenout)"
  echo "|"
  echo "|    Serial and local parallel operation execute directly; Cluster"
  echo "|    operation makes request to qsub."
  echo "|"
  echo "+==============================---------------------------------------"

  exit 0
fi

# --- Check for input file argument --- #
if [ -z "${2}" ]; then
  echo ">>> WARNING: Only runfile specified; Doing ./imogen serial ${2} 0 0"
  ./imogen serial ${2} 0 0
  exit 0
fi
RUNFILE=${2}

# --- Determine stream output --- #
stream=${3}
if [ -z "$3" ]; then
  stream="1"
fi
redirectStr="${HOME}/Results/logfile${stream}.out"

if [ -f "$redirectStr" ]; then
  echo ">>> NOTE: requested output stream exists; Appending."
fi


if [ ${1} = "serial" ]; then
  # ./imogen serial runfile stream GPU#
  gpuno=${4}
  if [ -z "$4" ]; then
    gpuno=0
    echo ">>> WARNING: defaulting to GPUs = [0]"
  fi

  echo "parImogenLoad('${RUNFILE}','${redirectStr}','${alias}',$gpuno);" | nohup nice matlab -nodisplay -nojvm >> $redirectStr & 
  exit 0
fi

if [ ${1} = "parallel" ]; then
  # ./imogen parallel runfile stream#  GPU# nprocs
  gpuno=${4}
  if [ -z "$4" ]; then
    gpuno=0
    echo ">>> WARNING: defaulting to GPUs = [0]"
  fi

  numproc=${5}
  if [ -z "$numproc" ]; then
    numproc=1
    echo ">>> WARNING: Parallel run defaulting to np=1"
  fi

  mpirun -np $numproc matlab -nodisplay -nojvm -r "parImogenLoad('${RUNFILE}','${redirectStr}','${alias}', $gpuno);" >> $redirectStr &

  exit 0
fi

if [ ${1} = "cluster" ]; then
# ./imogen cluster runfile stream #nodes PPN [np] queue
  gpuset=${4};
  if [ -z "$4" ]; then
    gpuset="[0]";
    echo ">>> WARNING: GPU selection defaulted to $gpuset"
  fi

  nnodes=${5};
  if [ -z "$5" ]; then
    nnodes="1";
    echo ">>> WARNING: # nodes defaulting to 1"
  fi

  procpn=${6};
  if [ -z "$6" ]; then
    procpn="1";
    echo ">>> WARNING: Processes/node defaulting to 1"
  fi

  QUEUE=${7}
  if [ -z "$7" ]; then
    QUEUE="gputest";
  fi

  NP=${8}
  if [ -z "$8" ]; then
    NP=$(expr $nnodes \* $procpn);
  fi


  TFILE=$(mktemp);

  echo "module load matlab/r2012b" >> $TFILE
  echo "module load mpi-tor/openmpi-1.5.4_gcc-4.5.3" >> $TFILE
  echo "module load cuda/5.5" >> $TFILE
  echo "echo PATH: \$PATH" >> $TFILE
  echo "cd $(pwd)" >> $TFILE
  echo "mpirun --mca btl_tcp_if_include torbr --bynode -np $NP matlab -nodisplay -nojvm -r \"parImogenLoad('${RUNFILE}','${redirectStr}','${alias}', $gpuset);\" " >> $TFILE

# This might be important, tell the user precisely how we're about to flush their cycles down the drain:
echo "CLUSTER IMOGEN RUN SETUP:"
echo "  $nnodes nodes"
echo "  $procpn processes/node"
echo "  Exact script that will be submitted to qsub:"
echo "------------------------------------------------------------"
cat $TFILE
echo "------------------------------------------------------------"
echo "  Into to queue $QUEUE"
echo "  using the following invocation:"
echo "qsub -q $QUEUE -l nodes=$nnodes:ppn=$procpn $TFILE -o $redirectStr"
echo -n "  In 5...";  sleep 1; echo -n "4... "; sleep 1; echo -n "3... "; sleep 1; echo -n "2... "; sleep 1; echo -n "1..."; sleep 1;

  qsub -j oe -q $QUEUE -l nodes=$nnodes:ppn=$procpn $TFILE -o $redirectStr
  #rm $TFILE
  exit 0
fi

echo ">>> ERROR: Did not receive usable arguments. See ./imogen help:"
./imogen help

